// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function HookEvents(d2: string, d3: string, d4: string, d5: string): $CancellablePromise<void> {
    return $Call.ByID(1580760459, d2, d3, d4, d5);
}
