// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class JSONSettings {
    "D2": string;
    "D3": string;
    "D4": string;
    "D5": string;

    /** Creates a new JSONSettings instance. */
    constructor($$source: Partial<JSONSettings> = {}) {
        if (!("D2" in $$source)) {
            this["D2"] = "";
        }
        if (!("D3" in $$source)) {
            this["D3"] = "";
        }
        if (!("D4" in $$source)) {
            this["D4"] = "";
        }
        if (!("D5" in $$source)) {
            this["D5"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JSONSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): JSONSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JSONSettings($$parsedSource as Partial<JSONSettings>);
    }
}
