// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.JSONSettings> {
    return $Call.ByID(1602601542).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HasSettings(): $CancellablePromise<boolean> {
    return $Call.ByID(1251142818);
}

export function InitializeSettingsService(): $CancellablePromise<string> {
    return $Call.ByID(2418592713);
}

export function SaveSettings(data: string): $CancellablePromise<void> {
    return $Call.ByID(944807473, data);
}

// Private type creation functions
const $$createType0 = $models.JSONSettings.createFrom;
