// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CloseConnection(): $CancellablePromise<void> {
    return $Call.ByID(5147213);
}

export function ConnectToCOM(port: string): $CancellablePromise<void> {
    return $Call.ByID(4279093251, port);
}

export function FindCOMPortAutomatically(): $CancellablePromise<string> {
    return $Call.ByID(4195334891);
}

export function GetCurrentCOMPortName(): $CancellablePromise<string> {
    return $Call.ByID(3037295383);
}

export function ListCOMPorts(): $CancellablePromise<string[]> {
    return $Call.ByID(3808457656).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReadData(d2: string, d3: string, d4: string, d5: string): $CancellablePromise<void> {
    return $Call.ByID(3075083751, d2, d3, d4, d5);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
